### ISSUE TITLE
Missing bin directory

### ISSUE THREAD

**Issue by robsyme** [viash-io/viash_project_template#6]
Hi Viash team

The quickstart tutorial provides a [project overview](https://viash.io/quickstart/#step-2-project-overview) that indicates the repository contains a `bin` directory, but I don't see one in this repository. Did I do something wrong, or is the repo incorrect, or is the viash quickstart guide behind?

**Comment by rcannood** [comment]
Hey Robert,

Thanks for letting me know about this :) The `bin/` directory got removed from the template a week or so ago because it is no longer needed. However, I'd forgotten to update the quickstart at viash.io accordingly. 

Merging viash-io/website#21 should have solved the issue. If not, please let me know and I'll reopen the issue.

Kind regards,
Robrecht
